/*
 * YtelAPIV3.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Utilities;

namespace YtelAPIV3.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum AudioDirection29Enum
    {
        IN, //TODO: Write general description for this method
        OUT, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type AudioDirection29Enum
    /// </summary>
    public static class AudioDirection29EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "in", "out" };

        /// <summary>
        /// Converts a AudioDirection29Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The AudioDirection29Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(AudioDirection29Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case AudioDirection29Enum.IN:
                case AudioDirection29Enum.OUT:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of AudioDirection29Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of AudioDirection29Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<AudioDirection29Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into AudioDirection29Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed AudioDirection29Enum value</returns>
        public static AudioDirection29Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type AudioDirection29Enum", value));

            return (AudioDirection29Enum) index;
        }
    }
} 