/*
 * YtelAPIV3.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Utilities;

namespace YtelAPIV3.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Direction23Enum
    {
        IN, //in direction
        OUT, //out direction
        BOTH, //both
    }

    /// <summary>
    /// Helper for the enum type Direction23Enum
    /// </summary>
    public static class Direction23EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "in", "out", "both" };

        /// <summary>
        /// Converts a Direction23Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Direction23Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Direction23Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Direction23Enum.IN:
                case Direction23Enum.OUT:
                case Direction23Enum.BOTH:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Direction23Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Direction23Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Direction23Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Direction23Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Direction23Enum value</returns>
        public static Direction23Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Direction23Enum", value));

            return (Direction23Enum) index;
        }
    }
} 