/*
 * YtelAPIV3.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Utilities;

namespace YtelAPIV3.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum NumbertypeEnum
    {
        ALL, //TODO: Write general description for this method
        VOICE, //TODO: Write general description for this method
        SMS, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type NumbertypeEnum
    /// </summary>
    public static class NumbertypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "all", "voice", "sms" };

        /// <summary>
        /// Converts a NumbertypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The NumbertypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(NumbertypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case NumbertypeEnum.ALL:
                case NumbertypeEnum.VOICE:
                case NumbertypeEnum.SMS:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of NumbertypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of NumbertypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<NumbertypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into NumbertypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed NumbertypeEnum value</returns>
        public static NumbertypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type NumbertypeEnum", value));

            return (NumbertypeEnum) index;
        }
    }
} 