/*
 * YtelAPIV3.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Utilities;

namespace YtelAPIV3.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum NumberType24Enum
    {
        ALL, //Get all phone Number type
        VOICE, //Get only voice number type
        SMS, //Get Only SMs number type
    }

    /// <summary>
    /// Helper for the enum type NumberType24Enum
    /// </summary>
    public static class NumberType24EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "all", "voice", "sms" };

        /// <summary>
        /// Converts a NumberType24Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The NumberType24Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(NumberType24Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case NumberType24Enum.ALL:
                case NumberType24Enum.VOICE:
                case NumberType24Enum.SMS:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of NumberType24Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of NumberType24Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<NumberType24Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into NumberType24Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed NumberType24Enum value</returns>
        public static NumberType24Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type NumberType24Enum", value));

            return (NumberType24Enum) index;
        }
    }
} 