/*
 * YtelAPIV3.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Utilities;
using YtelAPIV3.Standard.Http.Request;
using YtelAPIV3.Standard.Http.Response;
using YtelAPIV3.Standard.Http.Client;
using YtelAPIV3.Standard.Exceptions;

namespace YtelAPIV3.Standard.Controllers
{
    public partial class SharedShortCodeController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static SharedShortCodeController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static SharedShortCodeController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new SharedShortCodeController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// The response returned here contains all resource properties associated with the given Shortcode.
        /// </summary>
        /// <param name="shortcode">Required parameter: List of valid Shortcode to your Ytel account</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateViewShortcode(string shortcode)
        {
            Task<string> t = CreateViewShortcodeAsync(shortcode);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// The response returned here contains all resource properties associated with the given Shortcode.
        /// </summary>
        /// <param name="shortcode">Required parameter: List of valid Shortcode to your Ytel account</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateViewShortcodeAsync(string shortcode)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/shortcode/viewshortcode.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "Shortcode", shortcode )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// View a set of properties for a single keyword.
        /// </summary>
        /// <param name="keywordid">Required parameter: The unique identifier of each keyword</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateViewKeyword(string keywordid)
        {
            Task<string> t = CreateViewKeywordAsync(keywordid);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// View a set of properties for a single keyword.
        /// </summary>
        /// <param name="keywordid">Required parameter: The unique identifier of each keyword</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateViewKeywordAsync(string keywordid)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/keyword/view.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "Keywordid", keywordid )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// View a Shared ShortCode Template
        /// </summary>
        /// <param name="templateId">Required parameter: The unique identifier for a template object</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateViewTemplate(Guid templateId)
        {
            Task<string> t = CreateViewTemplateAsync(templateId);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// View a Shared ShortCode Template
        /// </summary>
        /// <param name="templateId">Required parameter: The unique identifier for a template object</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateViewTemplateAsync(Guid templateId)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/template/view.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "TemplateId", templateId )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// List All Inbound ShortCode
        /// </summary>
        /// <param name="datecreated">Optional parameter: Only list messages sent with the specified date</param>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: Number of individual resources listed in the response per page</param>
        /// <param name="mfrom">Optional parameter: From Number to Inbound ShortCode</param>
        /// <param name="shortcode">Optional parameter: Only list messages sent to this Short Code</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateListInboundSMS(
                string datecreated = null,
                int? page = null,
                int? pagesize = null,
                string mfrom = null,
                string shortcode = null)
        {
            Task<string> t = CreateListInboundSMSAsync(datecreated, page, pagesize, mfrom, shortcode);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// List All Inbound ShortCode
        /// </summary>
        /// <param name="datecreated">Optional parameter: Only list messages sent with the specified date</param>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: Number of individual resources listed in the response per page</param>
        /// <param name="mfrom">Optional parameter: From Number to Inbound ShortCode</param>
        /// <param name="shortcode">Optional parameter: Only list messages sent to this Short Code</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateListInboundSMSAsync(
                string datecreated = null,
                int? page = null,
                int? pagesize = null,
                string mfrom = null,
                string shortcode = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/shortcode/getinboundsms.json");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "Datecreated", datecreated }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "page", page ),
                new KeyValuePair<string, object>( "pagesize", pagesize ),
                new KeyValuePair<string, object>( "from", mfrom ),
                new KeyValuePair<string, object>( "Shortcode", shortcode )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Send an SMS from a Ytel ShortCode
        /// </summary>
        /// <param name="shortcode">Required parameter: The Short Code number that is the sender of this message</param>
        /// <param name="to">Required parameter: A valid 10-digit number that should receive the message</param>
        /// <param name="templateid">Required parameter: The unique identifier for the template used for the message</param>
        /// <param name="data">Required parameter: format of your data, example: {companyname}:test,{otpcode}:1234</param>
        /// <param name="method">Optional parameter: Specifies the HTTP method used to request the required URL once the Short Code message is sent.</param>
        /// <param name="messageStatusCallback">Optional parameter: URL that can be requested to receive notification when Short Code message was sent.</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateSendSMS(
                string shortcode,
                string to,
                Guid templateid,
                string data,
                string method = null,
                string messageStatusCallback = null)
        {
            Task<string> t = CreateSendSMSAsync(shortcode, to, templateid, data, method, messageStatusCallback);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Send an SMS from a Ytel ShortCode
        /// </summary>
        /// <param name="shortcode">Required parameter: The Short Code number that is the sender of this message</param>
        /// <param name="to">Required parameter: A valid 10-digit number that should receive the message</param>
        /// <param name="templateid">Required parameter: The unique identifier for the template used for the message</param>
        /// <param name="data">Required parameter: format of your data, example: {companyname}:test,{otpcode}:1234</param>
        /// <param name="method">Optional parameter: Specifies the HTTP method used to request the required URL once the Short Code message is sent.</param>
        /// <param name="messageStatusCallback">Optional parameter: URL that can be requested to receive notification when Short Code message was sent.</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateSendSMSAsync(
                string shortcode,
                string to,
                Guid templateid,
                string data,
                string method = null,
                string messageStatusCallback = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/shortcode/sendsms.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "shortcode", shortcode ),
                new KeyValuePair<string, object>( "to", to ),
                new KeyValuePair<string, object>( "templateid", templateid ),
                new KeyValuePair<string, object>( "data", data ),
                new KeyValuePair<string, object>( "Method", method ),
                new KeyValuePair<string, object>( "MessageStatusCallback", messageStatusCallback )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// List Shortcode Templates by Type
        /// </summary>
        /// <param name="type">Optional parameter: The type (category) of template Valid values: marketing, authorization</param>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: The count of objects to return per page.</param>
        /// <param name="shortcode">Optional parameter: Only list templates of type</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateListTemplates(
                string type = null,
                int? page = null,
                int? pagesize = null,
                string shortcode = null)
        {
            Task<string> t = CreateListTemplatesAsync(type, page, pagesize, shortcode);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// List Shortcode Templates by Type
        /// </summary>
        /// <param name="type">Optional parameter: The type (category) of template Valid values: marketing, authorization</param>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: The count of objects to return per page.</param>
        /// <param name="shortcode">Optional parameter: Only list templates of type</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateListTemplatesAsync(
                string type = null,
                int? page = null,
                int? pagesize = null,
                string shortcode = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/template/lists.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "type", type ),
                new KeyValuePair<string, object>( "page", page ),
                new KeyValuePair<string, object>( "pagesize", pagesize ),
                new KeyValuePair<string, object>( "Shortcode", shortcode )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Retrieve a list of keywords associated with your Ytel account.
        /// </summary>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: Number of individual resources listed in the response per page</param>
        /// <param name="keyword">Optional parameter: Only list keywords of keyword</param>
        /// <param name="shortcode">Optional parameter: Only list keywords of shortcode</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateListKeywords(
                int? page = null,
                int? pagesize = null,
                string keyword = null,
                int? shortcode = null)
        {
            Task<string> t = CreateListKeywordsAsync(page, pagesize, keyword, shortcode);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Retrieve a list of keywords associated with your Ytel account.
        /// </summary>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: Number of individual resources listed in the response per page</param>
        /// <param name="keyword">Optional parameter: Only list keywords of keyword</param>
        /// <param name="shortcode">Optional parameter: Only list keywords of shortcode</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateListKeywordsAsync(
                int? page = null,
                int? pagesize = null,
                string keyword = null,
                int? shortcode = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/keyword/lists.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "page", page ),
                new KeyValuePair<string, object>( "pagesize", pagesize ),
                new KeyValuePair<string, object>( "Keyword", keyword ),
                new KeyValuePair<string, object>( "Shortcode", shortcode )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Retrieve a list of shortcode assignment associated with your Ytel account.
        /// </summary>
        /// <param name="shortcode">Optional parameter: Only list keywords of shortcode</param>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: Number of individual resources listed in the response per page</param>
        /// <return>Returns the string response from the API call</return>
        public string CreateListShortcodes(string shortcode = null, int? page = null, int? pagesize = null)
        {
            Task<string> t = CreateListShortcodesAsync(shortcode, page, pagesize);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Retrieve a list of shortcode assignment associated with your Ytel account.
        /// </summary>
        /// <param name="shortcode">Optional parameter: Only list keywords of shortcode</param>
        /// <param name="page">Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.</param>
        /// <param name="pagesize">Optional parameter: Number of individual resources listed in the response per page</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> CreateListShortcodesAsync(string shortcode = null, int? page = null, int? pagesize = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/shortcode/listshortcode.json");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "Shortcode", shortcode }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "page", page ),
                new KeyValuePair<string, object>( "pagesize", pagesize )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Update Assignment
        /// </summary>
        /// <param name="shortcode">Required parameter: List of valid shortcode to your Ytel account</param>
        /// <param name="friendlyName">Optional parameter: User generated name of the shortcode</param>
        /// <param name="callbackUrl">Optional parameter: URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.</param>
        /// <param name="callbackMethod">Optional parameter: Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.</param>
        /// <param name="fallbackUrl">Optional parameter: URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST.</param>
        /// <param name="fallbackUrlMethod">Optional parameter: Specifies the HTTP method used to request the required FallbackUrl once call connects.</param>
        /// <return>Returns the string response from the API call</return>
        public string UpdateShortcode(
                string shortcode,
                string friendlyName = null,
                string callbackUrl = null,
                string callbackMethod = null,
                string fallbackUrl = null,
                string fallbackUrlMethod = null)
        {
            Task<string> t = UpdateShortcodeAsync(shortcode, friendlyName, callbackUrl, callbackMethod, fallbackUrl, fallbackUrlMethod);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Update Assignment
        /// </summary>
        /// <param name="shortcode">Required parameter: List of valid shortcode to your Ytel account</param>
        /// <param name="friendlyName">Optional parameter: User generated name of the shortcode</param>
        /// <param name="callbackUrl">Optional parameter: URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.</param>
        /// <param name="callbackMethod">Optional parameter: Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.</param>
        /// <param name="fallbackUrl">Optional parameter: URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST.</param>
        /// <param name="fallbackUrlMethod">Optional parameter: Specifies the HTTP method used to request the required FallbackUrl once call connects.</param>
        /// <return>Returns the string response from the API call</return>
        public async Task<string> UpdateShortcodeAsync(
                string shortcode,
                string friendlyName = null,
                string callbackUrl = null,
                string callbackMethod = null,
                string fallbackUrl = null,
                string fallbackUrlMethod = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/shortcode/updateshortcode.json");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "Shortcode", shortcode ),
                new KeyValuePair<string, object>( "FriendlyName", friendlyName ),
                new KeyValuePair<string, object>( "CallbackUrl", callbackUrl ),
                new KeyValuePair<string, object>( "CallbackMethod", callbackMethod ),
                new KeyValuePair<string, object>( "FallbackUrl", fallbackUrl ),
                new KeyValuePair<string, object>( "FallbackUrlMethod", fallbackUrlMethod )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields, Configuration.BasicAuthUserName, Configuration.BasicAuthPassword);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return _response.Body;
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 