/*
 * YtelAPIV3.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Utilities; 
using YtelAPIV3.Standard.Http.Client;
using YtelAPIV3.Standard.Http.Response;
using YtelAPIV3.Tests.Helpers;
using NUnit.Framework;
using YtelAPIV3.Standard;
using YtelAPIV3.Standard.Controllers;
using YtelAPIV3.Standard.Exceptions;

namespace YtelAPIV3.Tests
{
    [TestFixture]
    public class ShortCodeControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static ShortCodeController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().ShortCode;
        }

        /// <summary>
        /// Retrieve a list of Short Code assignment associated with your Ytel account. 
        /// </summary>
        [Test]
        public async Task TestTestListShortcodes() 
        {
            // Parameters for the API call
            string shortcode = null;
            string page = null;
            string pagesize = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListShortcodesAsync(shortcode, page, pagesize);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// Retrieve a list of Short Code messages. 
        /// </summary>
        [Test]
        public async Task TestTestListSMS() 
        {
            // Parameters for the API call
            string shortcode = null;
            string to = null;
            string dateSent = null;
            int? page = null;
            int? pageSize = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListSMSAsync(shortcode, to, dateSent, page, pageSize);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

        /// <summary>
        /// Retrive a list of inbound Sms Short Code messages associated with your Ytel account. 
        /// </summary>
        [Test]
        public async Task TestTestListInboundSMS() 
        {
            // Parameters for the API call
            int? page = null;
            int? pagesize = null;
            string mfrom = null;
            string shortcode = null;
            string datecreated = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListInboundSMSAsync(page, pagesize, mfrom, shortcode, datecreated);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

    }
}